name: ai_habit_tracking_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  firebase_auth: ^5.5.0
  firebase_core: ^3.12.0
  fl_chart: ^0.70.2
  flutter_svg: ^2.0.10+1
  curved_navigation_bar: ^1.0.6
  intl: ^0.19.0
  date_picker_timeline: ^1.2.5
  material_floating_search_bar_2: ^0.5.0
  font_awesome_flutter: ^10.1.0
  image_picker: ^0.8.4+3
  table_calendar: ^3.1.3
  cloud_firestore: ^5.6.5
  flutter_easyloading: ^3.0.5
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^6.1.4
  flutter_local_notifications: ^19.0.0
  firebase_messaging: ^15.2.4
  flutter_timezone: ^4.1.0
  tflite_flutter: ^0.11.0
  flutter_emoji_feedback: ^1.0.3
  timezone: ^0.10.0
  shared_preferences: ^2.5.3
  http: ^1.3.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/cover.png
    - assets/google.png
    - assets/apple.png
    - assets/notask.jpg
    - assets/profile.png
    - assets/habit_recommender.tflite
    - assets/habit_labels.txt
  #   - images/a_dot_ham.jpeg